Update spice_clone.py
Dabbing-Guy/spice_clone pull request #6
Opened 2023-03-21 18:59 UTC by Ascent817

2023-03-21 19:00 UTC, Ascent817 commented
Michael you should give me contributor access

2023-03-21 22:06 UTC, Dabbing-Guy commented
Varun, fix your pr and I'll merge it

2023-03-21 22:08 UTC, Dabbing-Guy commented
Also, you should use a better name for your commit, like "add more possible responses" or something: "Update spice_clone.py" is pretty vague.

2023-03-22 00:36 UTC, Dabbing-Guy requested changes

2023-03-22 00:36 UTC, VoidAny commented on spice_clone.py
> +    "Who asked"
There should be a comma at the end here

2023-03-22 01:03 UTC, Ascent817 commented on spice_clone.py
> +    "Who asked"
You have to approve the changes, I can't approve my own

2023-03-22 01:03 UTC, Ascent817 commented on spice_clone.py
> +    "Who asked"
It says that pr authors cannot approve changes

2023-03-22 01:04 UTC, Dabbing-Guy commented on spice_clone.py
> +    "Who asked"
I don't approve your changes in this pr though

2023-03-22 01:05 UTC, Dabbing-Guy approved these changes

2023-03-22 01:06 UTC, merged